version: '3.4'



services:
  apidb:
    container_name: apidb
    image: postgres:12
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - api
    environment:
      POSTGRES_USER: 'charisma'
      POSTGRES_PASSWORD: 'charisma'
      POSTGRES_DB: 'charisma-cms'
  api:
    container_name: api
    image: 402711366397.dkr.ecr.ap-south-1.amazonaws.com/charisma-api
    ports:
      - "5000:5000"
    depends_on:
      - apidb
    networks:
      - api
    environment:
      db_url: 'jdbc:postgresql://apidb:5432/charisma-cms'
      db_user: 'charisma'
      db_password: 'charisma'

#x-aws-cloudformation:
#  Resources:
#    ApiTCP8080TargetGroup:
#      Type: AWS::ElasticLoadBalancingV2::TargetGroup
#      Properties:
#        HealthCheckPath: /health
#        Matcher:
#          HttpCode: 200-499

volumes:
  pg-data:

networks:
  api: