name: Build and Verify Charisma API
on:
  push:
    branches:
      - integration_postgres_docker
  workflow_dispatch:


jobs:
  setup-build-package-publish:
    name: Setup, Clean , Test, Publish Test Coverage
    runs-on: ubuntu-latest

    services:
      postgres:
        # Docker Hub PostgreSQL image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: charisma
          POSTGRES_PASSWORD: pass123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    env:
      db_url: jdbc:postgresql://localhost:5432/charisma

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: JaCoCo coverage report
        run: ./gradlew clean test jacocoTestCoverageVerification --info

      - name: Build with Gradle
        run: ./gradlew build --info

      - name: Publish Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: 'test-report'
          path: build/reports/*
