name: Deploy Charisma API
on:
  workflow_dispatch:

jobs:
  setup-build-package-publish:
    name: Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew clean build --info

      # Setup gcloud CLI
      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Configure Docker with Credentials
      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      # Build the Docker image
      - name: Build Docker Image & Publish
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APPLICATION }}:${GITHUB_SHA}
      - name: Deploy
        run: |
          gcloud run deploy ${{ secrets.GCP_APPLICATION }} --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APPLICATION }}:${GITHUB_SHA} \
          --platform managed \
          --allow-unauthenticated \
          --memory 512M \
          --region europe-west2 \
          --project ${{ secrets.GCP_PROJECT_ID }}
